image: node:latest

stages:
  - setup
  - build
  - test

cache:
  key: ${CI_PIPELINE_ID}
  paths:
    - node_modules/
    - artifacts/
    - cache/

install_dependencies:
  stage: setup
  script:
    - npm install

compile_project:
  stage: build
  script:
    - npx hardhat compile

run_tests:
  stage: test
  script:
    - npx hardhat test
