image: node:20.12.x

stages:
  - test

cache:
  key: "solidity"
  paths:
    - node_modules/
    - artifacts/
    - cache/

run_tests:
  stage: test
  script:
    - echo "OWNER_KEY=${OWNER_KEY}" >> .env
    - npm install
    - npx hardhat compile
